### ISSUE TITLE
Rss problem

### ISSUE THREAD

**Issue by mezhevikin** [dbankier/XMLTools-For-Appcelerator-Titanium#4]
Use XMLTools for parsing RSS. Everything is working fine, but feed (http://habrahabr.ru/rss/best/)  returns:

``` javascript
{
      channel = "\n\t";
      version = "2.0";
}
```

In what may be problem? xml valid.

``` javascript
var url = 'http://habrahabr.ru/rss/best/';        
var client = Ti.Network.createHTTPClient();
client.open("GET", url, false);
client.send();

var XMLTools = require("XMLTools");
var xml = new XMLTools(client.responseText);
var my_object = xml.toObject();
Ti.API.info(my_object);
```

**Comment by mezhevikin** [comment]
I think the problem is due to <![CDATA[ ]] in tags

**Comment by dbankier** [comment]
The issue wasn't with the CDATA (even though it wasn't supported). It was with the Titanium XML parser interpreting "\n\t" as textContent. Have fixed it and added CDATA support. Should be good now.

**Comment by mezhevikin** [comment]
Cool :)
