### ISSUE TITLE
multiple passes through

### ISSUE THREAD

**Issue by jveal32** [dbankier/XMLTools-For-Appcelerator-Titanium#5]
Hi,
Ive successfully converted one xml file into a json output but when the same window needs to do it again, the results of the first parse are returned. Any thoughts? Do i need to manually reset some of the module variables before i can reuse it?
J

**Comment by Sophrinix** [comment]
I ran in this problem also. For right now use different variable name for each instance of the module you load.
Yes I realize that this defeats the whole point of CommonJS modules, but that's what I had to do.

When things slow down (haha) soon, I'll deep dive in to this issue. I am considering putting this module in the Appcelerator TCE training when we talk about network services.

**Comment by dbankier** [comment]
Sorry for the delay. Should be good  now.
