### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by junerockwell** [dbankier/XMLTools-For-Appcelerator-Titanium#6]
Error Domain=com.google.comGDataXML Code=-1 "The operation couldn't be completed. (com.google.GDataXML error -1)" at XMLTools.js (line 1)

I'm using XMLTools to parse my KML files and convert them into an object.

**Comment by dbankier** [comment]
generally invalid xml

**Comment by junerockwell** [comment]
Thanks!
